# Generated by Django 4.1 on 2022-08-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='data_comment',
            new_name='date_comment',
        ),
    ]
