# Generated by Django 4.0.6 on 2022-08-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la película', max_length=60)),
                ('description', models.TextField(help_text='Descripción de la película', max_length=200)),
                ('year', models.IntegerField(help_text='Año de la película')),
                ('image', models.ImageField(help_text='Imagen de la película', upload_to='movies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine_app.directores')),
            ],
        ),
    ]
